[package]
name = "lzjd-bin"
version = "0.2.0"
authors = ["Henk Dieter <henkdieter@tweedegolf.com>"]
edition = "2018"
exclude = ["in/*", "out/*"]
description = "Rust implementation of the LZJD algorithm (https://github.com/EdwardRaff/jLZJD)"
readme = "README.md"
keywords = ["lzjd", "edit", "distance", "Lempel", "Ziv"]
categories = ["algorithms","compression","cryptography","filesystem","science"]
license = "GPL-3.0"
repository = "https://github.com/tweedegolf/lzjd-rs"

[workspace]
members = [".", "lib"]

[dependencies]
lzjd = { path = "./lib" }
base64 = "0.10.1"
bincode = "1.1.2"
clap = "2.32.0"
failure = "0.1.5"
failure_derive = "0.1.5"
num_cpus = "1.10.0"
rayon = "1.0.3"
walkdir = "2.2.7"
